# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1399, 744)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 699))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("\\")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1381, 751))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b_ = QtWidgets.QPushButton(self.layoutWidget)
        self.b_.setMinimumSize(QtCore.QSize(0, 61))
        self.b_.setMouseTracking(False)
        self.b_.setAutoFillBackground(False)
        self.b_.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b_.setObjectName("b_")
        self.gridLayout.addWidget(self.b_, 4, 4, 1, 12)
        self.b1 = QtWidgets.QPushButton(self.layoutWidget)
        self.b1.setMinimumSize(QtCore.QSize(0, 61))
        self.b1.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 0, 0, 1, 1)
        self.bk = QtWidgets.QPushButton(self.layoutWidget)
        self.bk.setMinimumSize(QtCore.QSize(0, 61))
        self.bk.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bk.setObjectName("bk")
        self.gridLayout.addWidget(self.bk, 2, 15, 1, 2)
        self.b0 = QtWidgets.QPushButton(self.layoutWidget)
        self.b0.setMinimumSize(QtCore.QSize(0, 61))
        self.b0.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b0.setObjectName("b0")
        self.gridLayout.addWidget(self.b0, 0, 17, 1, 2)
        self.bh = QtWidgets.QPushButton(self.layoutWidget)
        self.bh.setMinimumSize(QtCore.QSize(0, 61))
        self.bh.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bh.setObjectName("bh")
        self.gridLayout.addWidget(self.bh, 2, 11, 1, 2)
        self.b9 = QtWidgets.QPushButton(self.layoutWidget)
        self.b9.setMinimumSize(QtCore.QSize(0, 61))
        self.b9.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 0, 15, 1, 2)
        self.bq = QtWidgets.QPushButton(self.layoutWidget)
        self.bq.setMinimumSize(QtCore.QSize(0, 61))
        self.bq.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;\n"
                              "")
        self.bq.setObjectName("bq")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bq)
        self.gridLayout.addWidget(self.bq, 1, 0, 1, 2)
        self.bb = QtWidgets.QPushButton(self.layoutWidget)
        self.bb.setMinimumSize(QtCore.QSize(0, 61))
        self.bb.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bb.setObjectName("bb")
        self.gridLayout.addWidget(self.bb, 3, 10, 1, 2)
        self.bs = QtWidgets.QPushButton(self.layoutWidget)
        self.bs.setMinimumSize(QtCore.QSize(0, 61))
        self.bs.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bs.setObjectName("bs")
        self.gridLayout.addWidget(self.bs, 2, 3, 1, 2)
        self.bj = QtWidgets.QPushButton(self.layoutWidget)
        self.bj.setMinimumSize(QtCore.QSize(0, 61))
        self.bj.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bj.setObjectName("bj")
        self.gridLayout.addWidget(self.bj, 2, 13, 1, 2)
        self.bp = QtWidgets.QPushButton(self.layoutWidget)
        self.bp.setMinimumSize(QtCore.QSize(0, 61))
        self.bp.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bp.setObjectName("bp")
        self.buttonGroup.addButton(self.bp)
        self.gridLayout.addWidget(self.bp, 1, 18, 1, 1)
        self.ba = QtWidgets.QPushButton(self.layoutWidget)
        self.ba.setMinimumSize(QtCore.QSize(0, 61))
        self.ba.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.ba.setObjectName("ba")
        self.gridLayout.addWidget(self.ba, 2, 1, 1, 2)
        self.bu = QtWidgets.QPushButton(self.layoutWidget)
        self.bu.setMinimumSize(QtCore.QSize(0, 61))
        self.bu.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bu.setObjectName("bu")
        self.buttonGroup.addButton(self.bu)
        self.gridLayout.addWidget(self.bu, 1, 12, 1, 2)
        self.bg = QtWidgets.QPushButton(self.layoutWidget)
        self.bg.setMinimumSize(QtCore.QSize(0, 61))
        self.bg.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bg.setObjectName("bg")
        self.gridLayout.addWidget(self.bg, 2, 9, 1, 2)
        self.bi = QtWidgets.QPushButton(self.layoutWidget)
        self.bi.setMinimumSize(QtCore.QSize(0, 61))
        self.bi.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bi.setObjectName("bi")
        self.buttonGroup.addButton(self.bi)
        self.gridLayout.addWidget(self.bi, 1, 14, 1, 2)
        self.bv = QtWidgets.QPushButton(self.layoutWidget)
        self.bv.setMinimumSize(QtCore.QSize(0, 61))
        self.bv.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bv.setObjectName("bv")
        self.gridLayout.addWidget(self.bv, 3, 8, 1, 2)
        self.bc = QtWidgets.QPushButton(self.layoutWidget)
        self.bc.setMinimumSize(QtCore.QSize(0, 61))
        self.bc.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bc.setObjectName("bc")
        self.gridLayout.addWidget(self.bc, 3, 6, 1, 2)
        self.b6 = QtWidgets.QPushButton(self.layoutWidget)
        self.b6.setMinimumSize(QtCore.QSize(0, 61))
        self.b6.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;\n"
                              "")
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 0, 9, 1, 2)
        self.b4 = QtWidgets.QPushButton(self.layoutWidget)
        self.b4.setMinimumSize(QtCore.QSize(0, 61))
        self.b4.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 0, 5, 1, 2)
        self.b7 = QtWidgets.QPushButton(self.layoutWidget)
        self.b7.setMinimumSize(QtCore.QSize(0, 61))
        self.b7.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;\n"
                              "\n"
                              "")
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 0, 11, 1, 2)
        self.bx = QtWidgets.QPushButton(self.layoutWidget)
        self.bx.setMinimumSize(QtCore.QSize(0, 61))
        self.bx.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bx.setObjectName("bx")
        self.gridLayout.addWidget(self.bx, 3, 4, 1, 2)
        self.about = QtWidgets.QPushButton(self.layoutWidget)
        self.about.setMinimumSize(QtCore.QSize(0, 23))
        self.about.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.about.setObjectName("about")
        self.gridLayout.addWidget(self.about, 7, 16, 1, 2)
        self.b8 = QtWidgets.QPushButton(self.layoutWidget)
        self.b8.setMinimumSize(QtCore.QSize(0, 61))
        self.b8.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 0, 13, 1, 2)
        self.bt = QtWidgets.QPushButton(self.layoutWidget)
        self.bt.setMinimumSize(QtCore.QSize(0, 61))
        self.bt.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bt.setObjectName("bt")
        self.buttonGroup.addButton(self.bt)
        self.gridLayout.addWidget(self.bt, 1, 8, 1, 2)
        self.bl = QtWidgets.QPushButton(self.layoutWidget)
        self.bl.setMinimumSize(QtCore.QSize(0, 61))
        self.bl.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bl.setObjectName("bl")
        self.gridLayout.addWidget(self.bl, 2, 17, 1, 2)
        self.br = QtWidgets.QPushButton(self.layoutWidget)
        self.br.setMinimumSize(QtCore.QSize(0, 61))
        self.br.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.br.setObjectName("br")
        self.buttonGroup.addButton(self.br)
        self.gridLayout.addWidget(self.br, 1, 6, 1, 2)
        self.b3 = QtWidgets.QPushButton(self.layoutWidget)
        self.b3.setMinimumSize(QtCore.QSize(0, 61))
        self.b3.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 0, 3, 1, 2)
        self.b5 = QtWidgets.QPushButton(self.layoutWidget)
        self.b5.setMinimumSize(QtCore.QSize(0, 61))
        self.b5.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 0, 7, 1, 2)
        self.bn = QtWidgets.QPushButton(self.layoutWidget)
        self.bn.setMinimumSize(QtCore.QSize(0, 61))
        self.bn.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bn.setObjectName("bn")
        self.gridLayout.addWidget(self.bn, 3, 12, 1, 2)
        self.b2 = QtWidgets.QPushButton(self.layoutWidget)
        self.b2.setMinimumSize(QtCore.QSize(0, 61))
        self.b2.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 0, 1, 1, 2)
        self.bo = QtWidgets.QPushButton(self.layoutWidget)
        self.bo.setMinimumSize(QtCore.QSize(0, 61))
        self.bo.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bo.setObjectName("bo")
        self.buttonGroup.addButton(self.bo)
        self.gridLayout.addWidget(self.bo, 1, 16, 1, 2)
        self.bd = QtWidgets.QPushButton(self.layoutWidget)
        self.bd.setMinimumSize(QtCore.QSize(0, 61))
        self.bd.setAutoFillBackground(False)
        self.bd.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bd.setObjectName("bd")
        self.gridLayout.addWidget(self.bd, 2, 5, 1, 2)
        self.be = QtWidgets.QPushButton(self.layoutWidget)
        self.be.setMinimumSize(QtCore.QSize(0, 61))
        self.be.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.be.setObjectName("be")
        self.buttonGroup.addButton(self.be)
        self.gridLayout.addWidget(self.be, 1, 4, 1, 2)
        self.bw = QtWidgets.QPushButton(self.layoutWidget)
        self.bw.setMinimumSize(QtCore.QSize(0, 61))
        self.bw.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bw.setObjectName("bw")
        self.buttonGroup.addButton(self.bw)
        self.gridLayout.addWidget(self.bw, 1, 2, 1, 2)
        self.by = QtWidgets.QPushButton(self.layoutWidget)
        self.by.setMinimumSize(QtCore.QSize(0, 61))
        self.by.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.by.setObjectName("by")
        self.buttonGroup.addButton(self.by)
        self.gridLayout.addWidget(self.by, 1, 10, 1, 2)
        self.bz = QtWidgets.QPushButton(self.layoutWidget)
        self.bz.setMinimumSize(QtCore.QSize(0, 61))
        self.bz.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bz.setObjectName("bz")
        self.buttonGroup.addButton(self.bz)
        self.gridLayout.addWidget(self.bz, 3, 2, 1, 2)
        self.bm = QtWidgets.QPushButton(self.layoutWidget)
        self.bm.setMinimumSize(QtCore.QSize(0, 61))
        self.bm.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bm.setObjectName("bm")
        self.gridLayout.addWidget(self.bm, 3, 14, 1, 2)
        self.bf = QtWidgets.QPushButton(self.layoutWidget)
        self.bf.setMinimumSize(QtCore.QSize(0, 61))
        self.bf.setStyleSheet("color: rgb(85, 255, 255);\n"
                              "background-color: rgb(85, 85, 255);\n"
                              "border-radius: 20px;                     /* <----  20px  */ \n"
                              "border: 2px solid #094065;")
        self.bf.setObjectName("bf")
        self.gridLayout.addWidget(self.bf, 2, 7, 1, 2)
        self.help = QtWidgets.QPushButton(self.layoutWidget)
        self.help.setMinimumSize(QtCore.QSize(0, 23))
        self.help.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.help.setObjectName("help")
        self.gridLayout.addWidget(self.help, 7, 13, 1, 3)
        self.load = QtWidgets.QPushButton(self.layoutWidget)
        self.load.setMinimumSize(QtCore.QSize(0, 61))
        self.load.setStyleSheet("color:rgb(255, 255, 255) ;\n"
                                "background-color: rgb(0, 170, 255);\n"
                                "border-radius: 15px;                     /* <----  20px  */ \n"
                                "border: 2px solid #094065;")
        self.load.setObjectName("load")
        self.gridLayout.addWidget(self.load, 5, 7, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Magic keyboard"))
        self.b_.setText(_translate("MainWindow", "Swap"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.bk.setText(_translate("MainWindow", "k"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.bh.setText(_translate("MainWindow", "h"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.bq.setText(_translate("MainWindow", "q"))
        self.bb.setText(_translate("MainWindow", "b"))
        self.bs.setText(_translate("MainWindow", "s"))
        self.bj.setText(_translate("MainWindow", "j"))
        self.bp.setText(_translate("MainWindow", "p"))
        self.ba.setText(_translate("MainWindow", "a"))
        self.bu.setText(_translate("MainWindow", "u"))
        self.bg.setText(_translate("MainWindow", "g"))
        self.bi.setText(_translate("MainWindow", "i"))
        self.bv.setText(_translate("MainWindow", "v"))
        self.bc.setText(_translate("MainWindow", "c"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.bx.setText(_translate("MainWindow", "x"))
        self.about.setText(_translate("MainWindow", "About"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.bt.setText(_translate("MainWindow", "t"))
        self.bl.setText(_translate("MainWindow", "l"))
        self.br.setText(_translate("MainWindow", "r"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.bn.setText(_translate("MainWindow", "n"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.bo.setText(_translate("MainWindow", "o"))
        self.bd.setText(_translate("MainWindow", "d"))
        self.be.setText(_translate("MainWindow", "e"))
        self.bw.setText(_translate("MainWindow", "w"))
        self.by.setText(_translate("MainWindow", "y"))
        self.bz.setText(_translate("MainWindow", "z"))
        self.bm.setText(_translate("MainWindow", "m"))
        self.bf.setText(_translate("MainWindow", "f"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.load.setText(_translate("MainWindow", "Load or make new"))
